a=int(input("Enter a number"))
b=int(input("Enter a number"))
c=int(input("Enter a number"))
print("Addition of three numbers is",a+b+c)a=int(input("Enter a number"))
print("subtraction of two numbers",a-b)
print("multiplication",a*b*c)
print("division",a/b)
print("integer division",a//b)
print("reminder",c%a)
